//
// Created by wld on 17.01.23.
//

#ifndef E_VOTING_PACKETSKIND_H
#define E_VOTING_PACKETSKIND_H

enum SCHEDULE_STATE {
    SELF_MSGKIND_CONNECT,
    SELF_MSGKIND_SEND,
    SELF_MSGKIND_LISTEN,
    SELF_MSGKIND_LISTEN_END,
    SELF_MSGKIND_CLOSE,
    SELF_MSGKIND_INIT_SYNC,
    SELF_MSGKIND_FORWARD_SYNC_UP,
    SELF_MSGKIND_LISTEN_SYNC_UP,
    SELF_MSGKIND_LISTEN_SYNC_DOWN,
    SELF_MSGKIND_RETURN_SYNC_DOWN
};

enum APP_PACKET_KIND {
    APP_CONN_REQUEST, APP_CONN_REPLY, APP_SYNC_REQUEST, APP_SYNC_REPLY, APP_SYNC_RETURN
};

class VotingAppTag : public omnetpp::cObject {
    public: APP_PACKET_KIND kind;
};

#endif //E_VOTING_PACKETSKIND_H
